name: Report
version: ${project.version}
main: me.j_m.report.Report
api-version: 1.16
authors: [ J_M ]
description: report plugin

commands:
  report:
    usage: /report <player> [reason]
    description: report someone for cheating
    permission: report.report
  reports:
    usage: /reports
    description: admin panel to check reported players
    permission: report.admin
