name: Report
version: ${project.version}
main: me.j_m.report.Report
api-version: 1.16
authors: [ J_M ]
description: report plugin

commands:
  report:
    usage: /report <player> [reason]
    description: report someone for cheating
    permission: report.report
  reports:
    usage: /reports
    description: admin panel to check reported players
    permission: report.admin
  ban:
    usage: /ban <player> <time> <reason>
    description: bans a player for amount of time. Use perm instead of time to perm ban someone.
    permission: report.ban
  reload:
    usage: /reload
    description: reloads config files
    permission: report.reload
  mute:
    usage: /mute <player> <time> <reason>
    description: Mutes a player for amount of time. Use perm instead of time to perm mute someone.
    permission: report.mute
